### ISSUE TITLE
Update usage instructions in README

### ISSUE THREAD

**Issue by schanzen** [reclaimID/client#1]
They are incorrect.

**Comment by kiliant** [comment]
still incorrect, making some adjustments in ./reclaim also

**Comment by kiliant** [comment]
will revert locally, work on optimising the script a little bit and then submit my changes as PR

**Comment by schanzen** [comment]
The problem is that for the user it is intransparent weather or not to call "reclaim stop" or "reclaim stop_demo". (same with purge)
It should be transparent to the user how the (initial) deployment is configured.

**Comment by kiliant** [comment]
the actions stop and purge should now be argument-agnostic
